spring:
  config:
    import: optional:file:.env[.properties]
  datasource:
    driver-class-name: ${SPRING_DATASOURCE_DRIVER_CLASS_NAME}
    username: ${SPRING_DATASOURCE_USERNAME}
    url: ${SPRING_DATASOURCE_URL}
    password: ${SPRING_DATASOURCE_PASSWORD}
  data:
    mongodb:
      uri: mongodb://ssafy:ssafy@i11a803.p.ssafy.io:27017/haribo?authSource=admin

jpa:
  properties:
    hibernate:
      dialect: org.hibernate.dialect.MySQLDialect
      format_sql: 'true'
      use_sql_comments: 'true'
      show_sql: 'true'
  hibernate:
    ddl-auto: ${DDL_AUTO}
  application:
    name: ${APPLICATION_NAME}

server:
  port : ${SERVER_PORT}

base:
  login-member-url : http://localhost:8080/api/v1/auth/profile
